/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-1",
    "aws_cognito_identity_pool_id": "ap-northeast-1:5cc18128-9ba2-493a-b81d-a60bff3e088b",
    "aws_cognito_region": "ap-northeast-1",
    "aws_user_pools_id": "ap-northeast-1_YJT0cZMYl",
    "aws_user_pools_web_client_id": "5v8cspu3bivoju3as8g8ovgm00",
    "oauth": {}
};


export default awsmobile;
